# Generated by Django 3.1.7 on 2021-03-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название статуса'),
        ),
    ]
