# Generated by Django 3.1.7 on 2021-03-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210315_0507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
